### ISSUE TITLE
SSH command and etherwake command

### ISSUE THREAD

**Issue by airbillion** [dmitryint/docker-duplicati#24]
I am trying to wake my backup server via a script that runs before the backup starts, but it is not possible because the etherwake command is not found...

I am also trying to send a sleep command to my backup server when the backup is finished, but the ssh command is not installed either...

Would it be poossibel to add these commands to the docker so pre/post backup scripts can execute these commands?

It would be a tremendous help!!

Thanks!

**Comment by dmitryint** [comment]
You can do this in a script by adding it to the `/docker-entrypoint-init.d/` directory.
Something like:
```
apt-get update && apt-get install -y ...
```

**Comment by airbillion** [comment]
Hello,

Thank you!  That worked...I created a script in that mapped directory and it installed ssh and etherwake when I pulled a fresh container!

Thanks!
