### ISSUE TITLE
Rockstor - Duplicati Rock-on

### ISSUE THREAD

**Issue by cameramanscott** [dmitryint/docker-duplicati#28]
I am trying to configure the Duplicati Rock-on and I am attempting to backup a Samba Share.  However when I am in the GUI for Duplicati I can not select the Share.  I have attached 2 images, the first one shows the treeview in Duplicati and the second shows the treeview from WINSCP.  The Share I want to backup is located under "mnt2", however that location is not visible in Duplicati.

Appreciate any help.  I attempted to add the path /mnt2/"share name"/ however I get an error message from Duplicati advising me location doesn't exist.

Cheers

![duplicati-rockstor-issue-image2](https://user-images.githubusercontent.com/29434875/27138606-eaf15622-50ee-11e7-80ba-027570d554e2.JPG)

![duplicati-rockstor-issue-image1](https://user-images.githubusercontent.com/29434875/27138460-820a26ac-50ee-11e7-89fa-59568df182c3.JPG)

**Comment by dmitryint** [comment]
This repository contains only Docker stuff.

To contact the author of the Duplicati, please use this repository: https://github.com/duplicati/duplicati
